### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by MikaelMelkonyan** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#10]
Hello.

I use "iOS Auto Provision with App Store Connect API" step in my workflow in the Bitrise. Version 0.1.0.
I have some error. Could you please help me to understand what am I doing wrong?

If you need some additional information, please let me know

```
panic: runtime error: slice bounds out of range [5:4] [recovered]
	panic: runtime error: slice bounds out of range [5:4]
goroutine 1 [running]:
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist.(*Encoder).Encode.func1(0xc000144aa8)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist/encode.go:29 +0xd1
panic(0x13a23a0, 0xc000bff1c0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist.(*textPlistGenerator).plistQuotedString(0xc000b29d00, 0xc0005c052e, 0xf, 0x4, 0x8)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist/text_generator.go:42 +0x613
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist.(*textPlistGenerator).writePlistValue(0xc000b29d00, 0x1472e60, 0xc000aef4d0)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist/text_generator.go:134 +0xf22
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist.(*textPlistGenerator).writePlistValue(0xc000b29d00, 0x14721a0, 0xc000ae7ec0)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist/text_generator.go:116 +0xe24
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist.(*textPlistGenerator).writePlistValue(0xc000b29d00, 0x14721a0, 0xc000a0cde0)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist/text_generator.go:116 +0xe24
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist.(*textPlistGenerator).writePlistValue(0xc000b29d00, 0x14721a0, 0xc000a0cdb0)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist/text_generator.go:116 +0xe24
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist.(*textPlistGenerator).generateDocument(0xc000b29d00, 0x14721a0, 0xc000a0cdb0)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist/text_generator.go:28 +0x3f
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist.(*Encoder).Encode(0xc000144ac0, 0x1396840, 0xc0006f3ad0, 0x0, 0x0)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist/encode.go:50 +0x248
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist.MarshalIndent(0x1396840, 0xc0006f3ad0, 0x3, 0x0, 0x0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist/encode.go:122 +0xbd
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist.Marshal(...)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/howett.net/plist/encode.go:113
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/github.com/bitrise-io/xcode-project/xcodeproj.XcodeProj.savePBXProj(0xc000602c93, 0x18, 0xc000602ddb, 0x18, 0xc000613f3d, 0x7, 0xc00033c640, 0x2, 0x2, 0xc00012a240, ...)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/github.com/bitrise-io/xcode-project/xcodeproj/xcodeproj.go:483 +0x61
github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/github.com/bitrise-io/xcode-project/xcodeproj.XcodeProj.Save(...)
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/vendor/github.com/bitrise-io/xcode-project/xcodeproj/xcodeproj.go:478
main.main()
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-go-toolkit398496058/src/github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/main.go:628 +0x2938
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ios-auto-provision-appstoreconnect@0 (exit code: 2)           | 54.55 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...se-steplib/steps-ios-auto-provision-appstoreconnect/issues |
| Source: ...thub.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect |
+---+---------------------------------------------------------------+----------+
```

**Comment by Robert-Bitrise** [comment]
Hi @MikaelMelkonyan,

Could you please check that you don't have any special characters or emojis in your XCode project folder names? If the plist contains any special characters/emojis then the iOS Auto Provision step can fail. I hope these information could help.

**Comment by MikaelMelkonyan** [comment]
> Hi @MikaelMelkonyan,
> 
> Could you please check that you don't have any special characters or emojis in your XCode project folder names? If the plist contains any special characters/emojis then the iOS Auto Provision step can fail. I hope these information could help.

Hello Robert. Thanks for your reply. 
I have 🚀 emoji in my 'Display name'. Is it required to remove emoji? For us it's very important to have emoji in 'Display name'. Marketing requirements 😃.

**Comment by Robert-Bitrise** [comment]
Hi @MikaelMelkonyan !

Sorry but you need to remove them if you want to be able to build :( Emojis are so funny and cool but it causes issues in the plist process.

**Comment by MikaelMelkonyan** [comment]
> Hi @MikaelMelkonyan !
> 
> Sorry but you need to remove them if you want to be able to build :( Emojis are so funny and cool but it causes issues in the plist process.

Got it. But old version of Auto-provision (iOS Auto Provision with Apple ID) still works fine with emojis. ((

**Comment by Robert-Bitrise** [comment]
@MikaelMelkonyan You are right. The old step has a different source code. You can use that step as an alternative solution for now, but that step will be deprecated. In the future our engineers will investigate the difference between the old and the new step's source code, but until then you can't use emojis if you want to use the new step. Thanks for your understanding.

**Comment by MikaelMelkonyan** [comment]
> @MikaelMelkonyan You are right. The old step has a different source code. You can use that step as an alternative solution for now, but that step will be deprecated. In the future our engineers will investigate the difference between the old and the new step's source code, but until then you can't use emojis if you want to use the new step. Thanks for your understanding.

Sure. I understand. Thanks a lot for your reply. 🤗

**Comment by iamcam** [comment]
I'm seeing this somewhat suddenly as well, though I don't have any emoji in my file path or display name. However, we did add some emoji to an Xcode build phase script, which I imagine must have done it. After removing the emoji builds are back to normal.

Is there any chance at all this bug can be resolved? Obviously it's no longer urgent for us, but a resolution would be appreciated.

Thanks!
